### ISSUE TITLE
Provide manylinux wheels

### ISSUE THREAD

**Issue by mcleantom** [CNES/pangeo-pyinterp#21]
**Is your feature request related to a problem? Please describe.**
I have a really old version of CentOS on the server where I want to use this package and I also dont have sudo privileges so installing packages with custom c++ code can be difficult. Providing pre-built wheels built inside a manylinux container solves these issues for me (as well as making the package quicker to install).

**Describe the solution you'd like**
Create python wheels inside a manylinux container and publish those to pypi.

**Describe alternatives you've considered**
None. My user account is heavily restricted so I don't have many options on what I can do!

**Additional context**
I have done this sort of thing before but I haven't ran it with github workflows (i've done it with Jenkins).

There are some example workflows here:

* https://github.com/scikit-image/scikit-image/blob/main/.github/workflows/wheel_tests_and_release.yml
* https://github.com/scipy/scipy/blob/main/.github/workflows/wheels.yml

And an [example](https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml) in the [cibuildwheel](https://github.com/pypa/cibuildwheel) package

```
name: Build and upload to PyPI

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]
# Alternatively, to publish when a (published) GitHub Release is created, use the following:
# on:
#   push:
#   pull_request:
#   release:
#     types:
#       - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    # upload to PyPI on every tag starting with 'v'
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    # alternatively, to publish when a GitHub Release is created, use the following rule:
    # if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          # To test: repository_url: https://test.pypi.org/legacy/
```

I am happy to try implement this myself and do a PR.
